django_Rest_tutorial/django_Rest/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('restapi/', include('djangorestapp.urls')),
]

django_Rest_tutorial/djangorestapp/urls.py
from django.urls import path
from djangorestapp.models import Article

from rest_framework.authtoken import views
 
 
from .views import *
app_name = 'restapi'
urlpatterns = [
         
         
        path('regi/',registerUser.some,name='some'),
        path('register/', registerUser.as_view(),name='register'),
        
        
        

]

django_Rest_tutorial/djangorestapp/models.py
from django.db import models

# Create your models here.

class Article(models.Model):
    title = models.CharField(max_length=200)
    authorname=models.CharField(max_length=200)
    email = models.EmailField(max_length=20)
    date = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.title

django_Rest_tutorial/djangorestapp/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.db.models import fields
from djangorestapp import models
from django.contrib.auth.models import User

class article(forms.ModelForm):
    class Meta:
        model = models.Article
        fields= "__all__"

class createuserform(UserCreationForm):
    class Meta:
        model=User
        fields= "__all__"

django_Rest_tutorial/djangorestapp/views.py
from django.contrib.auth.models import User
from djangorestapp.serializer import UserSerializer
from django.shortcuts import render,get_object_or_404,redirect
from djangorestapp.models import Article
from django.template import response
from rest_framework import serializers
from djangorestapp.serializer import ArticleSerializer
from django.template.response import TemplateResponse
from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponse,JsonResponse, request
from rest_framework.parsers import JSONParser
from rest_framework.decorators import api_view
from rest_framework.response import Response
from rest_framework import status
from rest_framework.views import APIView
from rest_framework.authtoken.models import Token
from djangorestapp import forms
from django.contrib.auth.forms import UserCreationForm
from .forms import createuserform

class ArticleList(APIView):
    def get(self,request):
       arti=Article.objects.all()
       serializer = ArticleSerializer(arti, many=True)
       return Response(serializer.data)    
    def post(self,request):
            
            serializer=ArticleSerializer(data=request.data)
            if serializer.is_valid():
                 serializer.save()
                 return Response(serializer.data,status=status.HTTP_200_OK)

            return Response(serializer.errors, status=status.HTTP_200_OK)

class ArticleDetails(APIView):
            def get_objects(self,id):
                   
                        return Article.objects.get(id)
                     
            def get(self,request,id):
                arti=self.get_objects(id)
                serializer= ArticleSerializer(arti)
                return Response(serializer.data) 

            def put(self,request,id):
                serializer=ArticleSerializer(data=request.data)
                if serializer.is_valid:
                    
                    serializer.save()
                    return Response(serializer.data,status=status.HTTP_200_OK)

                return Response(serializer.data,status=status.HTTP_200_OK)
            def delete(self,request,id):
                arti=self.get_objects(id)
                arti.delete()
                return Response(status=status.HTTP_405_METHOD_NOT_ALLOWED)

class registerUser(APIView):
    def some(request):
         
        from1=forms.createuserform()
        print(from1)

        return render(request,'index.html',{'userform': from1})
        
        
    def get(self,requset):
        print("gese")
        return render(request, "index.html")
    def post(self,request): 
       
            serializer=UserSerializer(data=request.data,partial=True)
            if not serializer.is_valid():
                print()
            
            serializer.save()
            print(serializer.data)
            user= User.objects.get(username=serializer.data['username'])
            token_obj ,_ =Token.objects.get_or_create(user=user)
            

            
            print(serializer.data)
            return Response({'status':200,'payload': serializer.data,'token':str(token_obj)})
          
             
        

"""
# Create your views here.
@api_view(['GET','POST'])
def articlelist(request):
    if request.method == "GET":
       
        arti=Article.objects.all()
        serializer = ArticleSerializer(arti, many=True)
        return Response(serializer.data)
    elif request.method =="POST":
        data = JSONParser().parse(request)
        serializer=ArticleSerializer(data=data)
        if serializer.is_valid():
           serializer.save()
           return Response(serializer.data,status=status.HTTP_200_OK)
 
        return Response(serializer.errors, status=status.HTTP_200_OK)
    
 
@api_view(['GET','PUT','DELETE'])
def articledetails(request,pk):
        
            
             
   
        arti =Article.objects.get(pk=pk)
     
        if request.method=="GET":
            serializer= ArticleSerializer(arti)
            return Response(serializer.data)   
        if request.method =="PUT":        
             data = JSONParser().parse(request)
             serializer=ArticleSerializer(arti,data=data)
             if serializer.is_valid():
                serializer.save()
             return Response(serializer.data,status=status.HTTP_200_OK)
        if request.method == "DELETE":
            arti.delete()
            return Response(status=status.HTTP_200_OK)
        
         
"""

django_Rest_tutorial/djangorestapp/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Font Awesome -->
<link
href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css"
rel="stylesheet"
/>
<!-- Google Fonts -->
<link
href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
rel="stylesheet"
/>
<!-- MDB -->
<link
href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.6.0/mdb.min.css"
rel="stylesheet"
/>
<!-- MDB -->
<script
  type="text/javascript"
  src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.6.0/mdb.min.js"
></script>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
     
    {% block body_block%}
 
    {% endblock %}
</div>
</div>
</body>
</html>

django_Rest_tutorial/djangorestapp/templates/index.html
 
 {% extends 'base.html' %}  
 {% block body_block%}
    
      <div style="margin-left: 40%;margin-right:40%" >
       <h1>User Registration</h1>
       <form action="{% url 'restapi:register' %}" method="post" id="form">
              {% csrf_token %}
              
            
              <input type="username" class="form-control " name="username" id="" placeholder="Username"><br><br> 
              <input type="password" class="form-control" name="password" id="" placeholder="Password"><br><br> 
              
              <button type="submit"  class="btn btn-danger">Sing Up</button>
          
      </form>       
    
    
        

            
      </div>
{% endblock %}